name: Pictures App CI
on: 
  push:
    branches: [testing, main]
  pull_request:
    branches: [testing, main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Ckeckout
        uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
        
    
